//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class Employee_Master
{
    public decimal Emp_Id { get; set; }
    public string Emp_Name { get; set; }
    public Nullable<System.DateTime> D_O_B { get; set; }
    public Nullable<decimal> Age { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string Emp_Designation { get; set; }
    public Nullable<System.DateTime> D_O_J { get; set; }
    public Nullable<System.DateTime> D_O_E { get; set; }
    public Nullable<System.DateTime> D_O_M { get; set; }
    public string Contact_Number { get; set; }
    public string Email_ID { get; set; }
    public string Gender { get; set; }
    public Nullable<bool> IsDeleted { get; set; }
    public string Emp_Image { get; set; }
}

public partial class Employee_Subject
{
    public decimal Emp_Sub_Id { get; set; }
    public Nullable<decimal> Emp_Id { get; set; }
    public Nullable<decimal> Sub_Id { get; set; }
}

public partial class Exam_Master
{
    public decimal Exam_Id { get; set; }
    public string Exam_Name { get; set; }
    public Nullable<decimal> Duration { get; set; }
    public Nullable<decimal> N_O_Q { get; set; }
    public Nullable<System.DateTime> Date_Of_Exam { get; set; }
    public Nullable<bool> Allow_Practice { get; set; }
    public string Mode { get; set; }
    public Nullable<decimal> Sub_Id { get; set; }
    public Nullable<System.DateTime> D_O_E { get; set; }
    public Nullable<System.DateTime> D_O_M { get; set; }
    public Nullable<bool> IsDeleted { get; set; }
    public Nullable<bool> IsLocked { get; set; }
}

public partial class Exam_Question
{
    public decimal Exam_Question_Id { get; set; }
    public Nullable<decimal> Exam_Id { get; set; }
    public Nullable<decimal> Question_Id { get; set; }
}

public partial class Exam_Unit
{
    public decimal Exam_Unit_Id { get; set; }
    public Nullable<decimal> Exam_Id { get; set; }
    public Nullable<decimal> Unit_Id { get; set; }
}

public partial class Login_Master
{
    public decimal Login_Id { get; set; }
    public string Login_Name { get; set; }
    public string Login_Type { get; set; }
    public string Login_Password { get; set; }
    public Nullable<decimal> Emd_Id { get; set; }
    public Nullable<decimal> Stu_Id { get; set; }
    public Nullable<System.DateTime> D_O_E { get; set; }
    public Nullable<System.DateTime> D_O_M { get; set; }
    public string Security_Question { get; set; }
    public string Security_Answer { get; set; }
    public string Otp { get; set; }
    public Nullable<bool> IsOtpGenrate { get; set; }
    public Nullable<bool> IsDeleted { get; set; }
}

public partial class Question_Bank
{
    public decimal Question_Id { get; set; }
    public string Question { get; set; }
    public Nullable<decimal> Question_Type_Id { get; set; }
    public Nullable<decimal> Emp_Id { get; set; }
    public Nullable<decimal> Unit_Id { get; set; }
    public Nullable<System.DateTime> D_O_E { get; set; }
    public Nullable<System.DateTime> D_O_M { get; set; }
    public Nullable<bool> IsDeleted { get; set; }
}

public partial class Question_Option
{
    public decimal Option_Id { get; set; }
    public Nullable<decimal> Question_Id { get; set; }
    public string Option_Description { get; set; }
    public Nullable<bool> IsTrue { get; set; }
}

public partial class Question_Type
{
    public decimal Question_Type_Id { get; set; }
    public string Type_Name { get; set; }
    public Nullable<System.DateTime> D_O_E { get; set; }
    public Nullable<System.DateTime> D_O_M { get; set; }
    public Nullable<bool> IsDeleted { get; set; }
}

public partial class Result
{
    public decimal Result_Id { get; set; }
    public string Stu_Name { get; set; }
    public string Exam_Name { get; set; }
    public Nullable<decimal> N_O_Q { get; set; }
    public Nullable<decimal> N_C_A { get; set; }
    public Nullable<decimal> N_W_A { get; set; }
    public Nullable<decimal> Total_Score { get; set; }
    public Nullable<System.DateTime> D_O_E { get; set; }
    public Nullable<System.DateTime> D_O_M { get; set; }
}

public partial class Semester
{
    public decimal Sem_Id { get; set; }
    public string Sem_Description { get; set; }
    public Nullable<System.DateTime> D_O_E { get; set; }
    public Nullable<System.DateTime> D_O_M { get; set; }
    public Nullable<bool> IsDeleted { get; set; }
}

public partial class Student_Master
{
    public decimal Stu_Id { get; set; }
    public string Stu_Name { get; set; }
    public string Contact_Number { get; set; }
    public string Gender { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public Nullable<System.DateTime> D_O_B { get; set; }
    public Nullable<decimal> Age { get; set; }
    public string Email_Id { get; set; }
    public string Parents_ContactNo { get; set; }
    public string Parents_EmailId { get; set; }
    public Nullable<System.DateTime> D_O_J { get; set; }
    public Nullable<System.DateTime> D_O_E { get; set; }
    public Nullable<System.DateTime> D_O_M { get; set; }
    public string Stu_Image { get; set; }
    public Nullable<decimal> Sem_Id { get; set; }
    public Nullable<bool> IsDeleted { get; set; }
}

public partial class Subject_Master
{
    public decimal Sub_Id { get; set; }
    public string Sub_Description { get; set; }
    public Nullable<System.DateTime> D_O_E { get; set; }
    public Nullable<System.DateTime> D_O_M { get; set; }
    public Nullable<bool> IsDeleted { get; set; }
}

public partial class Subject_Semester
{
    public decimal SubSem_Id { get; set; }
    public Nullable<decimal> Sub_Id { get; set; }
    public Nullable<decimal> Sem_Id { get; set; }
}

public partial class SubjectView
{
    public decimal Sub_Id { get; set; }
    public string Sub_Description { get; set; }
    public Nullable<System.DateTime> D_O_E { get; set; }
    public Nullable<System.DateTime> D_O_M { get; set; }
    public Nullable<bool> IsDeleted { get; set; }
}

public partial class Unit
{
    public decimal Unit_Id { get; set; }
    public string Unit_Name { get; set; }
    public Nullable<decimal> SubSem_Id { get; set; }
    public string Unit_Description { get; set; }
    public Nullable<System.DateTime> D_O_E { get; set; }
    public Nullable<System.DateTime> D_O_M { get; set; }
    public Nullable<bool> IsDeleted { get; set; }
}

public partial class View_Exam_Question_Option
{
    public decimal Exam_Id { get; set; }
    public string Question { get; set; }
    public string Type_Name { get; set; }
    public string Option_Description { get; set; }
    public decimal Option_Id { get; set; }
    public Nullable<bool> IsTrue { get; set; }
    public decimal Question_Id { get; set; }
}

public partial class ViewExamQuestion
{
    public decimal Question_Id { get; set; }
    public string Question { get; set; }
    public string Exam_Name { get; set; }
    public decimal Exam_Id { get; set; }
    public Nullable<decimal> Duration { get; set; }
}

public partial class ViewExamUnit
{
    public decimal Exam_Id { get; set; }
    public string Exam_Name { get; set; }
    public decimal Unit_Id { get; set; }
    public string Unit_Name { get; set; }
}

public partial class ViewQuestion
{
    public decimal Question_Id { get; set; }
    public Nullable<decimal> Question_Type_Id { get; set; }
    public string Question { get; set; }
    public Nullable<System.DateTime> D_O_E { get; set; }
    public Nullable<System.DateTime> D_O_M { get; set; }
    public Nullable<decimal> Emp_Id { get; set; }
    public Nullable<decimal> Unit_Id { get; set; }
    public Nullable<bool> IsDeleted { get; set; }
}

public partial class ViewSemester
{
    public decimal Sem_Id { get; set; }
    public string Sem_Description { get; set; }
    public Nullable<System.DateTime> D_O_E { get; set; }
    public Nullable<System.DateTime> D_O_M { get; set; }
    public Nullable<bool> IsDeleted { get; set; }
}

public partial class ViewStudent_Result
{
    public decimal Result_Id { get; set; }
    public string Exam_Name { get; set; }
    public Nullable<decimal> N_O_Q { get; set; }
    public Nullable<decimal> N_C_A { get; set; }
    public Nullable<decimal> N_W_A { get; set; }
    public Nullable<decimal> Total_Score { get; set; }
    public Nullable<System.DateTime> D_O_E { get; set; }
    public string Stu_Name { get; set; }
    public string Email_Id { get; set; }
    public decimal Stu_Id { get; set; }
    public decimal Exam_Id { get; set; }
}
