//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class eduExamSoftDBEntities : DbContext
{
    public eduExamSoftDBEntities()
        : base("name=eduExamSoftDBEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public DbSet<Employee_Subject> Employee_Subject { get; set; }
    public DbSet<Exam_Question> Exam_Question { get; set; }
    public DbSet<Exam_Unit> Exam_Unit { get; set; }
    public DbSet<Question_Option> Question_Option { get; set; }
    public DbSet<Question_Type> Question_Type { get; set; }
    public DbSet<Semester> Semesters { get; set; }
    public DbSet<Subject_Master> Subject_Master { get; set; }
    public DbSet<Subject_Semester> Subject_Semester { get; set; }
    public DbSet<Unit> Units { get; set; }
    public DbSet<SubjectView> SubjectViews { get; set; }
    public DbSet<Employee_Master> Employee_Master { get; set; }
    public DbSet<Student_Master> Student_Master { get; set; }
    public DbSet<Exam_Master> Exam_Master { get; set; }
    public DbSet<ViewExamUnit> ViewExamUnits { get; set; }
    public DbSet<Login_Master> Login_Master { get; set; }
    public DbSet<ViewQuestion> ViewQuestions { get; set; }
    public DbSet<ViewExamQuestion> ViewExamQuestions { get; set; }
    public DbSet<Question_Bank> Question_Bank { get; set; }
    public DbSet<View_Exam_Question_Option> View_Exam_Question_Option { get; set; }
    public DbSet<ViewSemester> ViewSemesters { get; set; }
    public DbSet<Result> Results { get; set; }
    public DbSet<ViewStudent_Result> ViewStudent_Result { get; set; }
}
